/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizedRoutesRouteImport } from './routes/_authorizedRoutes'
import { Route as AuthorizationLoginRouteImport } from './routes/_authorization/Login'

const AuthorizedRoutesRoute = AuthorizedRoutesRouteImport.update({
  id: '/_authorizedRoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizationLoginRoute = AuthorizationLoginRouteImport.update({
  id: '/_authorization/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/Login': typeof AuthorizationLoginRoute
}
export interface FileRoutesByTo {
  '/Login': typeof AuthorizationLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authorizedRoutes': typeof AuthorizedRoutesRoute
  '/_authorization/Login': typeof AuthorizationLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Login'
  fileRoutesByTo: FileRoutesByTo
  to: '/Login'
  id: '__root__' | '/_authorizedRoutes' | '/_authorization/Login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthorizedRoutesRoute: typeof AuthorizedRoutesRoute
  AuthorizationLoginRoute: typeof AuthorizationLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorizedRoutes': {
      id: '/_authorizedRoutes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorization/Login': {
      id: '/_authorization/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof AuthorizationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthorizedRoutesRoute: AuthorizedRoutesRoute,
  AuthorizationLoginRoute: AuthorizationLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
